# Development formula for installing SMSC from source before the first tagged release.
# The release formula is generated by GoReleaser into the configured Homebrew tap.
class Smsc < Formula
  desc "TUI for applying package-manager release-age gates"
  homepage "https://github.com/xavier/smsc"
  license "MIT"
  head "https://github.com/xavier/smsc.git", branch: "main"

  depends_on "go" => :build

  def install
    ldflags = "-s -w -X github.com/xavier/smsc/internal/app.version=#{version}"
    system "go", "build", *std_go_args(ldflags: ldflags), "./cmd/smsc"
  end

  test do
    system "#{bin}/smsc", "--version"
    system "#{bin}/smsc", "--help"
  end
end
